[["And they wishin' and wishin' and wishin' and wishin'They wishin' on me, yeah",
  "I been movin' calm, don't start no trouble with meTryna keep it peaceful is a struggle for me",
  "Don't pull up at 6 AM to cuddle with meYou know how I like it when you lovin' on me",
  "I don't wanna die for them to miss me", "Yes, I see the things that they wishin' on me",
  "Hope I got some brothers that outlive meThey gon' tell the story, shit was different with me",
  "God's plan, God's plan", "I hold back, sometimes I won't, yuh", "I feel good, sometimes I don't, ayy, don't",
  "I finessed down Weston Road, ayy, 'nessed", 'Might go down a G.O.D., yeah, wait',
  'I go hard on Southside G, yeah, wait', 'I make sure that north-side eat',
  "And still, bad thingsIt's a lot of bad thingsThat they wishin' and wishin' and wishin' and wishin'They wishin' on meBad thingsIt's a lot of bad thingsThat they wishin' and wishin' and wishin' and wishin'They wishin' on meYeah, ayy, ayy",
  'She say, "Do you love me?" I tell her, "Only partlyI only love my bed and my mama, I\'m sorry"',
  'Fifty Dub, I even got it tatted on me', "81, they'll bring the crashers to the party",
  'And you know meTurn the O2 into the O3, dog', "Without 40, Oli, there'd be no me'Magine if I never met the broskies",
  "God's plan, God's plan", "I can't do this on my own, ayy, no, ayySomeone watchin' this shit close, yep, close",
  "I've been me since Scarlett Road, ayy, road, ayy", 'Might go down as G.O.D., yeah, wait',
  'I go hard on Southside G, ayy, wait', 'I make sure that north-side eat, yeah',
  "And still, bad thingsIt's a lot of bad thingsThat they wishin' and wishin' and wishin' and wishin'They wishin' on me, yeah, yeahBad thingsIt's a lot of bad thingsThat they wishin' and wishin' and wishin' and wishin'They wishin' on me, yeah"],
 ["Astro, yeahSun is down, freezin' coldThat's how we already know, winter's here",
  "My dawg would probably do it for a Louis beltThat's just all he know, he don't know nothin' elseI tried to show 'em, yeahI tried to show 'em, yeah, yeah",
  "Yeah, yeah, yeahGoin' on you with the pick and roll", 'Young La Flame, he in sicko mode',
  'Woo, made this here with all the ice on in the booth', "Yeah, Jump Out boys, that's Nike boys, hoppin' out coupes",
  'This shit way too big, when we pull up, give me the loot(Gimme the loot!)', 'Was off the Remy, had a Papoose',
  'Had to hit my old town to duck the newsTwo-four hour lockdown, we made no moves',
  "Now it's 4 a.m. and I'm back up poppin' with the crew", 'I just landed in, Chase B mixes pop like Jamba Juice',
  "Different colored chains, think my jeweler really sellin' fruits",
  "And they chokin', man, know the crackers wish it was a noose",
  "Some—Some—Some—Someone saidTo win the retreat, we all in too deepPl—Pl—Playin' for keeps, don't play us for weak (Someone said)To win the retreat, we all in too deepPl-Pl-Playin' for keeps, don't play us for weak",
  "Yeah, this shit way too formal, y'all know I don't follow suit", "Stacey Dash, most of these girls ain't got a clue",
  "All of these hoes I made off records I producedI might take all my exes and put 'em all in a group",
  'Hit my eses, I need the bootch', '\'Bout to turn this function to BonnarooTold her, "Hop in, you comin\' too"',
  "In the 305, bitches treat me like I'm Uncle Luke(Don't stop, pop that pussy!)",
  "Had to slop the top off, it's just a roof, uh", 'She said, "Where we goin\'?" I said, "The moon"',
  "We ain't even make it to the roomShe thought it was the ocean, it's just the pool",
  "Now I got her open, it's just the Goose", "Who put this shit together? I'm the glue", 'Someone said',
  'Shorty FaceTimed me out the blue',
  "Someone saidPl—Playin' for keepsSomeone said, motherfucker—someone saidDon't play us for weak",
  '(Tay Keith, fuck these niggas up!)',
  'Back in high school, I used to bus it to the dance (Yeah)Now I hit the FBO with duffels in my hands',
  "I did half a Xan, 13 hours 'til I landHad me out like a light, ayy, yeahLike a light, ayy, yeah",
  'Like a light, ayy, slept through the flight, ayy',
  'Knocked for the night, ayy767, man, this shit got double bedroom, man', 'I still got scores to settle, man',
  'I crept down the block (Down the block)Made a right (Yeah, right)Cut the lights (Yeah, what?), paid the price (Yeah)',
  "Niggas think it's sweet (Nah, never), it's on sight (Yeah, what?)",
  "Nothin' nice (Yeah), baguettes in my ice (Aw, man)",
  "Jesus Christ (Yeah), checks over stripes (Yeah)That's what I like (Yeah), that's what we like (Yeah)",
  'Lost my respect, you not a threat', "When I shoot my shot, that shit wetty like I'm Sheck (Bitch)",
  "See the shots that I took (Ayy), wet like I'm Book (Ayy)", "Wet like I'm Lizzie",
  "I be spinnin' Valley, circle blocks 'til I'm dizzy (Yeah, what?)",
  'Back in high school, I used to bus it to the danceNow I hit the FBO with duffels in my hands (Woo)',
  "I did half a Xan, 13 hours 'til I landHad me out like a light (Like a light)Like a light (Like a light)Like a light (Like a light)Like a light",
  "Yeah, passed the dawgs a cellySendin' texts, ain't sendin' kites, yeah",
  'LaFerrari to Jamba Juice, yeah (Skrrt, skrrt)',
  "We back on the road, they jumpin' off, no parachute, yeahShawty in the backShe said she workin' on her glutes, yeah (Oh my God)",
  "Ain't by the book, yeah, this how it look, yeah", "'Bout a check, yeah (Check), just check the foots, yeah",
  "Pass this to my daughter, I'ma show her what it took (Yeah)",
  'Baby mama cover Forbes, got these other bitches shookYeah'], [
     'Work, work, work, work, work, workHe said me haffiWork, work, work, work, work, work!He see me do miDirt, dirt, dirt, dirt, dirt, dirt!So me put inWork, work, work, work, work, workWhen you ah guhLearn, learn, learn, learn, learnMeh nuh cyar if himHurt, hurt, hurt, hurt, hurting',
     'Dry! ...Me a desert himNuh time to have you lurkingHim ah go act like he nuh like itYou know I dealt with you the nicest',
     'Nuh badda, text me in a crisis',
     'I believed all of your dreams, adorationYou took my heart and my keys and my patience',
     'You took my heart on my sleeve for decoration',
     "You mistaken my love I brought for you for foundationAll that I wanted from you was to give meSomething that I never hadSomething that you've never seenSomething that you've never been!",
     "Mmmmm!But I wake up and act like nothing's wrongJust get ready fi...",
     'Work, work, work, work, work, workHe said me haffiWork, work, work, work, work, work!He see me do miDirt, dirt, dirt, dirt, dirt, dirt!So me put inWork, work, work, work, work, work',
     "Beg you something, pleaseBaby don't you leaveDon’t leave me stuck here in the streets, uh huhIf I get another chance toI will never, no never neglect you",
     'I mean who am I to hold your past against you?',
     "I just hope that it gets to youI hope that you see this throughI hope that you see this trueWhat can I say?Please recognize I'm tryin', babe!!!I have to",
     'Work, work, work, work, work, workHe said me haffiWork, work, work, work, work, work!He see me do miDirt, dirt, dirt, dirt, dirt, dirt!So me put inWork, work, work, work, work, workWhen you ah guhLearn, learn, learn, learn, learnMeh nuh cyar if himHurt, hurt, hurt, hurt, hurting',
     'Yeah, okayYou need to get done, done, done, done at work, come over', 'We just need to slow the motion',
     'If you had a twin, I would still choose you', "I don't wanna rush into it, if it's too soon",
     'But I know you need to get done, done, done, doneIf you come over',
     "Sorry if I'm way less friendlyI got niggas tryna end me, oh", 'I spilled all my emotions tonight, I’m sorry',
     "Rollin', rollin', rollin', rollin', rollin'How many more shots until you're rollin'?",
     'We just need a face to faceYou could pick the time and the placeYou spent some time awayNow you need to forward and give me all the...',
     'Work, work, work, work, work, workHe said me haffiWork, work, work, work, work, workHe se me do miDirt, dirt, dirt, dirt, dirt, dirt!So me put inWork, work, work, work, work, workWhen you ah guhLearn, learn, learn, learn, learnMeh nuh cyar if himHurt, hurt, hurt, hurt, hurting',
     'Mmmmm, mmmmmMmmmm, mmmmmWork, work, work, work, work, workMmmmm, mmmmm'], [
     "I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)",
     "If findin' somebody real is your fuckin' problem", 'Bring your girls to the crib, maybe we can solve it, ayy',
     'Make that thing pop like a semi or a 9', 'Ooh, baby like it raw with the shimmy shimmy ya, huh?',
     'A$AP (Yeah), get like me (Uh)',
     'Never met a motherfucker fresh like me (Yeah)All these motherfuckers wanna dress like me (Uh)',
     'But the chrome to your dome make you sweat like Keith',
     "‘Cause I'm the nigga, the nigga, nigga, like how you figure? (Yeah)Gettin' figures and fuckin' bitches",
     "she rollin' Swishers", 'She love my licorice, I let her lick it (Alright)',
     'They say money make a nigga act nigga-ish (Uh)But least a nigga, nigga rich',
     "I be fuckin' broads like I be fuckin' bored", "Turn a dyke bitch out, have her fuckin' boys, beast",
     "I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)",
     "If findin' somebody real is your fuckin' problemBring your girls to the crib, maybe we can solve it, ayy",
     'Ooh, I know you love it when this beat is on',
     "Make you think about all of the niggas you been leadin' onMake me think about all of the rappers I've been feedin' onGot a feelin' that's the same dudes that we speakin' on, oh word?",
     "Ain't heard my album? Who you sleepin' on?You should print the lyrics out and have a fuckin' read-along",
     "Ain't a fuckin' sing-along 'less you brought the weed along",
     'Then ju-, okay, I got itThen just drop down and get your eagle on',
     'Or we can stare up at the stars and put the Beatles on',
     "All that shit you talkin' 'bout is not up for discussionI will pay to make it bigger, I don't pay for no reduction",
     "If it's comin' from a nigga I don't know, then I don't trust it",
     "If you comin' for my head, then motherfucker get to bustin'", 'Yes, Lord,',
     "I don't really say this oftenBut this long-dick nigga ain't for the long talkin',", "I'm beast",
     "I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)",
     "If findin' somebody real is your fuckin' problemBring your girls to the crib, maybe we can solve it",
     'Uh, yeah, ho, this the finale', 'My pep talk turn into a pep rally',
     'Say she from the hood but she live inside in the valley, now',
     "Vacay'd in Atlanta, then she goin' back to Cali (Mmm)",
     "Got your girl on my line, world on my lineThe irony, I fuck 'em at the same damn time",
     "She eyein' me like a nigga don't existGirl, I know you want this dick", "Girl, I'm Kendrick Lamar (Mmm)",
     'A.K.A. Benz is to me just a car (Mmm)',
     'That mean your friends-es need be up to parSee, my standards are pampered by threesomes tomorrow (Mmm)',
     "Kill 'em all, dead bodies in the hallway", "Don't get involved, listen what the crystal ball say",
     "Halle Berry, hallelujahHoller back, I'll do ya, beast",
     "I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)I love bad bitches, that's my fuckin' problem (Problem)And yeah, I like to fuck, I got a fuckin' problem (Problem)",
     "If findin' somebody real is your fuckin' problemBring your girls to the crib, maybe we can solve it, ayy"],
 ['Trap, TrapMoneyBenny',
  "Kiki, do you love me? Are you riding?Say you'll never ever leave from beside me'Cause I want ya, and I need yaAnd I'm down for you alwaysKB, do you love me? Are you riding?Say you'll never ever leave from beside me'Cause I want ya, and I need yaAnd I'm down for you always",
  'Look, the new me is really still the real me', 'TrapMoneyBenny', 'I buy you Champagne but you love some Henny',
  'From the block like you Jenny',
  "'Resha, do you love me? Are you riding?Say you'll never ever leave from beside me'Cause I want ya, and I need yaAnd I'm down for you alwaysJ.T., do you love me? Are you riding?Say you'll never ever leave from beside me'Cause I want ya, and I need yaAnd I'm down for you always",
  'Magnolia Shorty',
  "Two bad bitches and we kissin' in the WraithKissin'-kissin' in the Wraith, kiss-kissin' in the Wraith",
  'I need that black card and the code to the safeCode to the safe, code-code to the safe-safe',
  'Yeah, yeah, yeah, yeah, he bad', "Yeah, yeah, yeah, guess who's back", 'Black biggy biggy black biggy black blake',
  'I got a new boy, and that nigga trade!',
  "Kiki, do you love me? Are you riding?Say you'll never ever leave from beside me'Cause I want you, and I need youAnd I'm down for you alwaysKB, do you love me? Are you riding?Say you'll never ever leave from beside me'Cause I want ya, and I–",
  'Skate and Smoke and RapNow let me see you',
  "Bring that ass, bring that ass, bring that ass back!B-bring that ass, bring that ass, bring that ass back!Shawty say the nigga that she with can't hitBut shawty, I'ma hit it, hit it like I can't miss",
  'Now let me see you', 'Bring that ass back!', 'Bring that ass back!', 'Trap, TrapMoneyBenny',
  "BlaqNmilD, you a genius, you diggin' me?"], ['You used to call me on myYou used to, you used toYeah',
                                                'You used to call me on my cell phoneLate-night when you need my loveCall me on my cell phoneLate-night when you need my love',
                                                'And I know when that hotline blingThat can only mean one thingI know when that hotline blingThat can only mean one thing',
                                                "Ever since I left the city, youGot a reputation for yourself nowEverybody knows and I feel left outGirl, you got me down, you got me stressed out'Cause ever since I left the city, youStarted wearing less and goin' out moreGlasses of champagne out on the dance floorHangin' with some girls I've never seen before",
                                                'You used to call me on my cell phoneLate-night when you need my loveCall me on my cell phoneLate-night when you need my love',
                                                'I know when that hotline blingThat can only mean one thingI know when that hotline blingThat can only mean one thing',
                                                "Ever since I left the city, you, you, youYou and me, we just don't get alongYou make me feel like I did you wrongGoing places where you don't belongEver since I left the city, youYou got exactly what you asked forRunning out of pages in your passportHangin' with some girls I've never seen before",
                                                'You used to call me on my cell phoneLate-night when you need my loveCall me on my cell phoneLate-night when you need my love',
                                                'And I know when that hotline blingThat can only mean one thingI know when that hotline blingThat can only mean one thing',
                                                "These days, all I do isWonder if you're bendin' over backwards for someone elseWonder if you're rolling up a Backwoods for someone else",
                                                "Doing things I taught you, gettin' nasty for someone elseYou don't need no one elseYou don't need nobody else, no",
                                                "Why you never alone?Why you always touching road?Used to always stay at homeBe a good girl, you was in the zoneYeah, you should just be yourselfRight now, you're someone else",
                                                'You used to call me on my cell phoneLate-night when you need my loveCall me on my cell phoneLate-night when you need my love',
                                                'And I know when that hotline blingThat can only mean one thingI know when that hotline blingThat can only mean one thing',
                                                'Ever since I left the city…'],
 ['Grips on your waist, front way, back way',
  "You know that I don't playStreets not safe but I never run awayEven when I'm away",
  "Oti, otiThere's never much love when we go OTI pray to make it back in one pieceI pray, I pray",
  "That's why I need a one danceGot a Hennessy in my handOne more time 'fore I goHigher powers taking a hold on meI need a one danceGot a Hennessy in my handOne more time 'fore I goHigher powers taking a hold on me",
  "Strength and guidanceAll that I'm wishing for my friends",
  'Nobody makes it from my endsI had to bust up the silence',
  "You know you gotta stick by meSoon as you see the text, reply meI don't wanna spend time fightingWe've got no time",
  "And that's why I need a one danceGot a Hennessy in my handOne more time 'fore I goHigher powers taking a hold on meI need a one danceGot a Hennessy in my handOne more time 'fore I goHigher powers taking a hold on me",
  'Got a pretty girl and she love me long timeWine it, wine it, very long timeOh yeah, very long timeBack up, back up, back up and wine itBack up, back up and wine it, girlBack up, back up, back up and wine itOh yeah, very long timeBack, up, back up and wine it, girl',
  "Oh yeah, very long timeWhere, where, whereBack, up, back up and wine it, girlWhere, where, where, whereCause if you're downBack up, back up andCause if you're downBack up, back up andCause if you're downBack up, back up and",
  "I need a one danceGot a Hennessy in my handOne more time 'fore I goHigher powers taking a hold on meI need a one danceGot a Hennessy in my handOne more time 'fore I goHigher powers taking a hold on me"],
 ["I got my eyes on youYou're everything that I seeI want your hot love and emotion endlessly",
  "I can't get over youYou left your mark on meI want your hot love and emotion endlessly",
  "'Cause you're a good girl and you know itYou act so different around me",
  "'Cause you're a good girl and you know itI know exactly who you could be",
  "Just hold on, we're going homeJust hold on, we're going home", "It's hard to do these things alone",
  "I got my eyes on youYou're everything that I seeI want your hot love and emotion endlessly",
  "I can't get over youYou left your mark on meI want your hot love and emotion endlessly",
  "'Cause you're a good girl and you know itYou act so different around me",
  "'Cause you're a good girl and you know itI know exactly who you could be",
  "Just hold on, we're going home (Going home)Just hold on, we're going home (Going home)",
  "It's hard to do these things alone (Things alone)",
  "'Cause you're a good girl and you know itYou act so different around me",
  "'Cause you're a good girl and you know itI know exactly who you could be",
  "Just hold on, we're going home (Going home)Just hold on, we're going home (Going home)",
  "It's hard to do these things alone (Things alone)"],
 ["Hol' it yute, hol' it, hol' it, hol' it, hol' it, hol' itNo sleepin' in the streets!Shaky warrior",
  "Yeah, this that Oliver, 40, Niko shit man15 Fort York shit, y'know?", "Boi-1da, what's poppin'?Yeah, yeah",
  "Runnin' through the 6 with my woesCountin' money, you know how it goes",
  'Pray the real live forever, manPray the fakes get exposed',
  'I want that Ferrari, then I swerveI want that Bugatti, just to hurt',
  "I ain't rockin' my jewelry, that's on purpose",
  "Niggas want my spot and don't deserve itI don't like how serious they take themselves",
  "I've always been me, I guess I know myselfShakiness, man, I don't have no time for that",
  "My city too turned up, I'll take the fine for thatThis been where you find me atThat's been where you find me at",
  'I know a nigga named Johnny BlingHe put me on to the finer things', "Had a job sellin' Girbaud jeans",
  'I had a yellow TechnoMarineThen Kanye dropped, it was polos and backpacks',
  "Man, that was when Ethan was pushin' a Subaru hatchback",
  "Man, I'm talkin' way before hashtagsI was runnin' through the 6 with my woes(Yeah!)",
  "I was runnin' through the 6 with my woesYou know how that should goYou know how that should goYou know how that should goRunnin' through the 6 with my woesYou know how that should goYou know how that should goYou know how that should go",
  "Don't fuck with them niggas, they too irrational, woah",
  "This is that nasty flowTop boy in this shit, I'm so international",
  'Reps up is in hereGot P Reign and Chubby and TJ and Winnie and whoaYeah, and you know how that should go',
  "I might declare it a holiday as soon as Baka get back on the roadYeah, but you know how that should goThey so irrational, they don't wanna patch it upThey wanna mash it up, woah",
  'My nigga Jibba, he whip it, I ride in the passenger',
  "I'm way up, I stay up, I'm two up, I'm three upI had to get back to you, woah",
  "I'm turnin' into a nigga that thinks about money and womenLike 24/7, that's where my life took meThat's just how shit happened to goAnd you knowRunnin' through the 6 with my, with my",
  "I was running through the 6 with my woesAnd you know how that should goYou know how that should goYou know how that should goRunnin' through the 6 with my woesYou know how that should goYou know how that should goYou know how that should goRunnin' through the 6 with my woesYou know how that should go",
  '...Shell out, all if yuh eye nuh bigAlways haffi look out, yuh no know if yuh head book out',
  'Dun know, a de Unruly boss, dis manNo bomboclat, otha', 'And if a boy nuh like OVO or Chromatic',
  'Yuh can jus suck yuh mada!!With no apology,', '(Machine gun shots)', 'With my woes'],
 ['Oh manOh man, oh manNot again', 'Yeah, I learned the game from William Wesley, you can never check me',
  "Back to back for the niggas that didn't get the messageBack to back, like I'm on the cover of Lethal WeaponBack to back, like I'm Jordan '96, '97",
  "Whoa—very important and very pretentiousWhen I look back, I might be mad that I gave this attentionYeah, but it's weighin' heavy on my conscience",
  'Yeah, and fuck, you left The Boy no optionsI wanna see my niggas go insane',
  "You gon' make me step out of my fuckin' frameYou gon' make me buy bottles for CharlamagneYou gon' make me go out of my fuckin' way",
  "I waited four days, nigga, where y'all at?I drove here in the Wraith playin' AR-AB",
  "I'm not sure what it was that really made y'all madBut I guess this is what I gotta do to make y'all rap",
  "I mean whoa, can't fool the city, man, they know what's upSecond floor at Tootsies, gettin' shoulder rubs",
  "This for y'all that think that I don't write enoughThey just mad 'cause I got the Midas touch",
  "You love her, then you gotta give the world to herIs that a world tour or your girl's tour?I know that you gotta be a thug for herThis ain't what she meant when she told you to open up more",
  "Yeah, trigger fingers turn to Twitter fingersYeah, you gettin' bodied by a singin' niggaI'm not the type of nigga that'll type to niggas",
  "And shout-out to all my boss bitches wifin' niggasMake sure you hit him with the prenupThen tell that man to ease up",
  "I did another one, I did another oneYou still ain't did shit about the other one",
  "I got the drink in me going back to backYeah, going back to backI got the drink in me going back to backYeah, I'm going back to back",
  'I don\'t wanna hear about this ever againNot even when she tell him that they better as friendsNot even when you saying, "Drizzy, tell \'em again!"',
  "I been puttin' on a show, it was a sell-out eventOh, you need better seatin'",
  "I didn't wanna do it, gave me every reasonThe point I'm tryin' to make is I don't ever need 'emSeen what you'd do for fame, what would you do for freedom?",
  "Please, check 'em for a wire or a earpiecePlease, please do not let these niggas near me",
  "Please, think before you come for the great onePlease, who's a real nigga and who ain't one?",
  "Please, somebody stop meI'm talkin' boasy and gwanin wassy",
  "I got the fest in five days and it's my shitSoon as a nigga hit the stage, they gon'[Chorus]They gon' ask if I can play this shit back to backYeah, they want it back to backThey gon' ask if I can play this shit back to back",
  "I took a break from Views, now it's back to that, nigga (Six)"],
 ['Every second, every minuteMan, I swear that she can get it',
  "Say if you a bad bitch, put your hands up highHands up high, hands up highTell 'em dim the lights down right nowPut me in the moodI'm talkin' about dark room, perfume, go, go",
  "I recognize your fragranceHold up, you ain't never gotta say shit", 'You live life on an everyday basis',
  'With poetic justice, poetic justice', 'If I told you that a flower bloomed in a dark roomWould you trust it?',
  'I mean, I write poems in these songs dedicated to you when',
  "You're in the mood for empathy, there's blood in my pen",
  "Better yet, where your friends and 'em?I really wanna know you all",
  "Nigga, don't approach her with that AtariNigga, that ain't good game, homie, sorry",
  'They say conversation rule a nation, I can tell',
  "But I could never right my wrongs'Less I write it down for real, P.S",
  'You can get it, you can get itYou can get it, you can get itAnd I know just, know just, know justKnow just, know just what you wantPoetic justice, put it in a song, alrightYou can get it, you can get itYou can get it, you can get itAnd I know just, know just, know justKnow just, know just what you wantPoetic justice, put it in a song, alright',
  "I really hope you play this, 'cause ol' girl, you test my patienceWith all these seductive photographsAnd all these one-off vacations you've been takin'Clearly a lot for me to take in,",
  "it don't make sense",
  "you too busy fuckin' with your other manI was tryna put you on game, put you on a planeTake you and your momma to the motherland",
  'That sound like poetic justice, poetic justice', 'I mean, I write poems in these songs, dedicated to the fun sex',
  "But I can never right my wrongsUnless I write 'em down for real, P.S",
  'You can get it, you can get itYou can get it, you can get itAnd I know just, know just, know justKnow just, know just what you wantPoetic justice, put it in a song, alrightYou can get it, you can get itYou can get it, you can get itAnd I know just, know just, know justKnow just, know just what you wantPoetic justice, put it in a song, alright',
  'Every time I write these words they become a taboo',
  "Makin' sure my punctuation curve, every letter here's trueLivin' my life in the margin and that metaphor was proof",
  "I'm talkin' poetic justice, poetic justice", 'If I told you that a flower bloomed in a dark roomWould you trust it?',
  "I mean, you need to hear thisLove is not just a verb, it's you lookin' in the mirrorLove is not just a verb, it's you lookin' for it, maybe",
  'A fatal attraction is common, and what we have common is pain',
  'I mean, you need to hear this, love is not just a verb',
  "And I can see power steerin', sex drive when you swerveI want that interference, it's coherent, I can hear it",
  'Sincerely, yours truly, and right before you go blind, P.S',
  'You can get it, you can get itYou can get it, you can get itAnd I know just, know just, know justKnow just, know just what you wantPoetic justice, put it in a song'],
 [
     "You're the only power (Power)You're the only power that canYou're the only power (Power)You're the only power that canOh, oh, oh, father...",
     "(If young Metro don't trust you, I'm gon' shoot you)",
     "Beautiful mornin', you're the sun in my mornin', babeWho can I turn to?Nothin' unwantedAfter all, who can I turn to?Beautiful mornin', you're the sun in my mornin', babeIf I don't turn to youNothin' unwantedNo other help I know, I stretch my hands",
     "I just wanna feel liberated, I-I, na-na-naWho can I turn to?I just wanna feel liberated, I-I, na-na-naAfter all, who can I turn to?If I ever instigated, I am sorryIf I don't turn to youTell me who in here could relate, I-I-INo other help I know, I stretch my hands",
     "Now, if I fuck this modelAnd she just bleached her assholeAnd I get bleach on my T-shirtI'ma feel like an asshole",
     'I was high when I met herWe was down in Tribeca',
     "She'll get under your skin if you let herShe'll get under your skin if you-uhI don't even wanna talk about itI don't even wanna talk about itI don't even wanna say nothin'",
     "Everybody gon' say somethin'I'd be worried if they said nothin'",
     "Remind me where I know you fromShe lookin' like she owe you some'n",
     'You know just what we wantI wanna wake up with you in my...I wanna wake up with you in my...',
     "Beautiful mornin', you're the sun in my mornin', babeWho can I turn to?Beautiful mornin'Nothin' unwantedAfter all, who can I turn to?Beautiful mornin', you're the sun in my mornin', babeIf I don't turn to youNothin' unwantedNo other help I know, I stretch my hands",
     "I just wanna feel liberated, I-I, na-na-naWho can I turn to?I just wanna feel liberated, I-I, na-na-naAfter all, who can I turn to?If I ever instigated, I am sorryIf I don't turn to youTell me who in here could relate, I-I-INo other help I know, I stretch my hands"]]
